// example-project/nuxt-app/app.vue
<script setup>
import { MyCheckbox, MyComponent, MyRange, MyRadioGroup } from 'component-library-vue'

function handleCheckboxChange(event) {
  console.log('Checkbox changed:', event.detail.checked)
}

</script>

<template>
  <div>
    <Input />
    <hr />
    <MyComponent first="Stencil" last="'Don't call me a framework' JS" />
    <hr />
    <MyRange name="myRange">Hello World</MyRange>
    <hr />
    <MyRadioGroup name="myRadioGroup" value="two">
      <input type="radio" name="myRadioGroup" value="one" />
      <input type="radio" name="myRadioGroup" value="two" />
      <input type="radio" name="myRadioGroup" value="three" />
    </MyRadioGroup>

    <MyCheckbox @ionChange="handleCheckboxChange">Checkbox!!!</MyCheckbox>
  </div>
</template>

// example-project/next-15-runtime-based/src/app/page.tsx
import {
  MyComponent,
  MyRange,
  MyCounter,
  MyRadioGroup,
  MyRadio,
} from 'component-library-react/next';
import Input from './Input/Input';
import Button from './Button/Button';
import { ToggleableContent } from './ToggleableContent/ToggleableContent';

function getStuff() {
  return 'I am random value!';
}

export default function Home() {
  return (
    <>
      <Input />
      <hr />
      <Button />
      <hr />
      <MyComponent
        first="Stencil"
        middleName={getStuff()}
        last="'Don't call me a framework' JS"
        className="my-8"
      />
      <hr />
      <MyRange name="myRange">Hello World</MyRange>
      <ToggleableContent />
      <hr />
      <MyCounter />
      <hr />
      <MyRadioGroup name="myRadio" value="foo">
        <MyRadio value="foo">Foo</MyRadio>
        <MyRadio value="bar">Bar</MyRadio>
        <MyRadio value="baz">Baz</MyRadio>
      </MyRadioGroup>
    </>
  );
}
