// example-project/vue-app/src/App.vue
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue'
// @ts-ignore
import Input from './components/Input.vue'
import { MyComponent, MyCheckbox } from 'component-library-vue'
import { ref } from 'vue'

const isClicked = ref(false)
const handleCustomEvent = () => {
  isClicked.value = true
}

const kidsNames = ['John', 'Jane']
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
  <MyComponent
    @myCustomEvent="handleCustomEvent"
    :kidsNames="kidsNames"
    first="John"
    middle="Sir"
    favoriteKidName="John"
    :age=20
    last="Doe"
  />
  <p data-testid="mycomponent-click" v-show="isClicked">MyComponent was clicked</p>
  <Input />
  <MyCheckbox @ionChange="console.log">Checkbox!!!</MyCheckbox>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// example-project/react-app/src/App.tsx
import './App.css'
import { useState } from 'react'
import Input from './Input/Input'
import { MyComponent, MyCounter } from 'component-library-react'
import reactLogo from './assets/react.svg'

function App() {
  const [count, setCount] = useState(0)

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src="/vite.svg" className="logo" alt="Vite logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
      <Input data-testid="inputCheck" />
      <MyComponent first="Don't" middle="😉" last="call me a framework" kidsNames={['John', 'Jane']} />
      <MyCounter />
    </>
  )
}

export default App
